### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by henkdebruijn** [bibene/upushover#1]
I get the following error:

Traceback (most recent call last):                                                                                                                    
  File "<stdin>", line 1, in <module>                                                                                                                 
  File "main.py", line 19, in <module>                                                                                                                
  File "upushover.py", line 27, in sendMessage                                                                                                        
AttributeError: 'module' object has no attribute 'IPPROTO_SEC'

**Comment by bibene** [comment]
On what version of micropython are you running it and on what device? If I am not mistaken I tested this on 1.8 micropython on a wipy device(on one of the first to be made - kickstarter reward).

**Comment by henkdebruijn** [comment]
I use version 1.8.6 (latest) on an esp8266 board (Feather Huzzah)

**Comment by bibene** [comment]
Could you try following
`import usocket as socket`
instead of
`import socket`
?

**Comment by henkdebruijn** [comment]
I tried, but still same error ;-(

Has it something to do with the type of board I use?

**Comment by bibene** [comment]
Could be. Here https://forum.micropython.org/viewtopic.php?t=2485 is a very similar issue, maybe you could try committing the last parameter.

**Comment by bibene** [comment]
Just found the related micropython issue: https://github.com/pycom/pycom-micropython/issues/52

**Comment by ijustwant** [comment]
I get the same message:
AttributeError: 'module' object has no attribute 'IPPROTO_SEC'

I'm using the "loboris/MicroPython_ESP32_psRAM_LoBo" build

Any way to get this working ? :)
